// =============================================================================
// ISKOlarship - User Model
// Based on ERD: User entity with Student and Admin profiles
// Aligned with Research Paper Entity Relationship Diagram
// =============================================================================

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

// =============================================================================
// Enums (matching ERD and frontend types)
// =============================================================================

const UserRole = {
  STUDENT: 'student',
  ADMIN: 'admin'
};

// Classification from ERD (year level/standing)
const Classification = {
  INCOMING_FRESHMAN: 'Incoming Freshman',
  FRESHMAN: 'Freshman',
  SOPHOMORE: 'Sophomore',
  JUNIOR: 'Junior',
  SENIOR: 'Senior',
  GRADUATE: 'Graduate'
};

// Alias for backward compatibility
const YearLevel = Classification;

// UPLB Colleges
const UPLBCollege = {
  CAS: 'College of Arts and Sciences',
  CAFS: 'College of Agriculture and Food Science',
  CEM: 'College of Economics and Management',
  CEAT: 'College of Engineering and Agro-Industrial Technology',
  CFNR: 'College of Forestry and Natural Resources',
  CHE: 'College of Human Ecology',
  CVM: 'College of Veterinary Medicine',
  CDC: 'College of Development Communication',
  CPAF: 'College of Public Affairs and Development',
  GS: 'Graduate School'
};

// ST Bracket (Socialized Tuition)
const STBracket = {
  FULL_DISCOUNT_WITH_STIPEND: 'Full Discount with Stipend',
  FULL_DISCOUNT: 'Full Discount',
  PD80: 'PD80',
  PD60: 'PD60',
  PD40: 'PD40',
  PD20: 'PD20',
  NO_DISCOUNT: 'No Discount'
};

// Admin Access Levels
const AdminAccessLevel = {
  UNIVERSITY: 'university',
  COLLEGE: 'college',
  DEPARTMENT: 'department'
};

// Citizenship options
const Citizenship = {
  FILIPINO: 'Filipino',
  DUAL_CITIZEN: 'Dual Citizen',
  FOREIGN: 'Foreign National'
};

// Philippine Provinces (for province_of_origin from ERD)
const PhilippineProvinces = [
  // NCR
  'Metro Manila',
  // Region I - Ilocos Region
  'Ilocos Norte', 'Ilocos Sur', 'La Union', 'Pangasinan',
  // Region II - Cagayan Valley
  'Batanes', 'Cagayan', 'Isabela', 'Nueva Vizcaya', 'Quirino',
  // Region III - Central Luzon
  'Aurora', 'Bataan', 'Bulacan', 'Nueva Ecija', 'Pampanga', 'Tarlac', 'Zambales',
  // Region IV-A - CALABARZON
  'Batangas', 'Cavite', 'Laguna', 'Quezon', 'Rizal',
  // Region IV-B - MIMAROPA
  'Marinduque', 'Occidental Mindoro', 'Oriental Mindoro', 'Palawan', 'Romblon',
  // Region V - Bicol Region
  'Albay', 'Camarines Norte', 'Camarines Sur', 'Catanduanes', 'Masbate', 'Sorsogon',
  // Region VI - Western Visayas
  'Aklan', 'Antique', 'Capiz', 'Guimaras', 'Iloilo', 'Negros Occidental',
  // Region VII - Central Visayas
  'Bohol', 'Cebu', 'Negros Oriental', 'Siquijor',
  // Region VIII - Eastern Visayas
  'Biliran', 'Eastern Samar', 'Leyte', 'Northern Samar', 'Samar', 'Southern Leyte',
  // Region IX - Zamboanga Peninsula
  'Zamboanga del Norte', 'Zamboanga del Sur', 'Zamboanga Sibugay',
  // Region X - Northern Mindanao
  'Bukidnon', 'Camiguin', 'Lanao del Norte', 'Misamis Occidental', 'Misamis Oriental',
  // Region XI - Davao Region
  'Davao de Oro', 'Davao del Norte', 'Davao del Sur', 'Davao Occidental', 'Davao Oriental',
  // Region XII - SOCCSKSARGEN
  'Cotabato', 'Sarangani', 'South Cotabato', 'Sultan Kudarat',
  // Region XIII - Caraga
  'Agusan del Norte', 'Agusan del Sur', 'Dinagat Islands', 'Surigao del Norte', 'Surigao del Sur',
  // BARMM
  'Basilan', 'Lanao del Sur', 'Maguindanao del Norte', 'Maguindanao del Sur', 'Sulu', 'Tawi-Tawi',
  // CAR
  'Abra', 'Apayao', 'Benguet', 'Ifugao', 'Kalinga', 'Mountain Province'
];

// =============================================================================
// User Schema - Based on ERD
// =============================================================================

const userSchema = new mongoose.Schema({
  // =========================================================================
  // USER Entity Fields (from ERD)
  // user_id: auto-generated by MongoDB (_id)
  // =========================================================================
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,
    lowercase: true,
    trim: true,
    match: [/^\S+@\S+\.\S+$/, 'Please provide a valid email']
  },
  password: {
    type: String,
    required: [true, 'Password is required'],
    minlength: [8, 'Password must be at least 8 characters'],
    select: false
  },
  role: {
    type: String,
    enum: Object.values(UserRole),
    required: true,
    default: UserRole.STUDENT
  },
  
  // Additional authentication fields
  isActive: {
    type: Boolean,
    default: true
  },
  isEmailVerified: {
    type: Boolean,
    default: false
  },
  
  // Refresh tokens for session management
  refreshTokens: [{
    token: String,
    createdAt: { type: Date, default: Date.now }
  }],
  
  lastLoginAt: Date,
  
  // =========================================================================
  // STUDENT Entity Fields (from ERD - IS A relationship with USER)
  // student_id: auto-generated, user_id: reference to this document
  // =========================================================================
  studentProfile: {
    // Student Number (student_id in ERD context)
    studentNumber: {
      type: String,
      sparse: true,
      unique: true
    },
    
    // Name (composite attribute in ERD)
    firstName: {
      type: String,
      trim: true
    },
    middleName: {
      type: String,
      trim: true
    },
    lastName: {
      type: String,
      trim: true
    },
    suffix: {
      type: String,
      trim: true,
      enum: ['', 'Jr.', 'Sr.', 'II', 'III', 'IV', 'V']
    },
    
    // home_address (from ERD)
    homeAddress: {
      street: String,
      barangay: String,
      city: String,
      province: String,
      zipCode: String,
      fullAddress: String // Computed full address
    },
    
    // province_of_origin (from ERD) - Important for location-based scholarships
    provinceOfOrigin: {
      type: String,
      enum: PhilippineProvinces
    },
    
    // college (from ERD)
    college: {
      type: String,
      enum: Object.values(UPLBCollege)
    },
    
    // course (from ERD)
    course: {
      type: String,
      trim: true
    },
    
    // Major (sub-specialization)
    major: {
      type: String,
      trim: true
    },
    
    // classification (from ERD) - Year level/standing
    classification: {
      type: String,
      enum: Object.values(Classification)
    },
    
    // gwa (from ERD) - General Weighted Average
    gwa: {
      type: Number,
      min: 1.0,
      max: 5.0
    },
    
    // units_count (from ERD) - Units enrolled
    unitsEnrolled: {
      type: Number,
      min: 0,
      max: 30
    },
    
    // Total units passed (for thesis grant eligibility)
    unitsPassed: {
      type: Number,
      min: 0
    },
    
    // family_income (from ERD) - Annual family income
    annualFamilyIncome: {
      type: Number,
      min: 0
    },
    
    // citizenship (from ERD)
    citizenship: {
      type: String,
      enum: Object.values(Citizenship),
      default: Citizenship.FILIPINO
    },
    
    // Household size (for income bracket computation)
    householdSize: {
      type: Number,
      min: 1,
      max: 20
    },
    
    // ST Bracket (Socialized Tuition)
    stBracket: {
      type: String,
      enum: Object.values(STBracket)
    },
    
    // Expected graduation
    expectedGraduationYear: Number,
    expectedGraduationSemester: {
      type: String,
      enum: ['First', 'Second', 'Midyear']
    },
    
    // Contact Information
    contactNumber: String,
    birthDate: Date,
    
    // =====================================================================
    // Scholarship Eligibility Status Fields
    // =====================================================================
    
    // Current scholarship status (for mustNotHaveOtherScholarship criteria)
    hasExistingScholarship: {
      type: Boolean,
      default: false
    },
    existingScholarshipName: String,
    
    // Thesis grant status (for mustNotHaveThesisGrant criteria)
    hasThesisGrant: {
      type: Boolean,
      default: false
    },
    
    // Academic standing flag (for mustNotHaveDisciplinaryAction criteria)
    hasDisciplinaryAction: {
      type: Boolean,
      default: false
    },
    
    // Profile completion tracking
    profileCompleted: {
      type: Boolean,
      default: false
    },
    profileCompletedAt: Date
  },
  
  // =========================================================================
  // ADMIN Entity Fields (from ERD - IS A relationship with USER)
  // admin_id: auto-generated, user_id: reference to this document
  // =========================================================================
  adminProfile: {
    // Personal Information
    firstName: String,
    lastName: String,
    
    // department (from ERD)
    department: {
      type: String,
      trim: true
    },
    
    // College affiliation
    college: {
      type: String,
      enum: [...Object.values(UPLBCollege), null]
    },
    
    // Position/Title
    position: {
      type: String,
      trim: true
    },
    
    // Office location/building
    officeLocation: {
      type: String,
      trim: true
    },
    
    // Primary responsibilities
    responsibilities: {
      type: String,
      trim: true
    },
    
    // Contact address (for admin profile)
    address: {
      street: String,
      barangay: String,
      city: String,
      zipCode: String,
      fullAddress: String
    },
    
    // access_level (from ERD)
    accessLevel: {
      type: String,
      enum: Object.values(AdminAccessLevel),
      default: AdminAccessLevel.DEPARTMENT
    },
    
    // Permissions array for granular control
    permissions: [{
      type: String,
      enum: [
        'manage_scholarships',
        'review_applications',
        'approve_applications',
        'manage_users',
        'view_analytics',
        'system_settings'
      ]
    }]
  }
}, {
  timestamps: true
});

// =============================================================================
// Indexes
// =============================================================================

userSchema.index({ 'studentProfile.college': 1 });
userSchema.index({ 'studentProfile.classification': 1 });
userSchema.index({ 'studentProfile.provinceOfOrigin': 1 });
userSchema.index({ 'studentProfile.gwa': 1 });
userSchema.index({ 'studentProfile.annualFamilyIncome': 1 });
userSchema.index({ role: 1 });
userSchema.index({ isActive: 1 });

// =============================================================================
// Pre-save Middleware
// =============================================================================

userSchema.pre('save', async function(next) {
  // Hash password if modified
  if (!this.isModified('password')) return next();
  
  const salt = await bcrypt.genSalt(12);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

// Update profile completion status
userSchema.pre('save', function(next) {
  if (this.role === UserRole.STUDENT && this.studentProfile) {
    const profile = this.studentProfile;
    const isComplete = !!(
      profile.firstName &&
      profile.lastName &&
      profile.college &&
      profile.course &&
      profile.classification &&
      profile.gwa !== undefined &&
      profile.annualFamilyIncome !== undefined &&
      profile.citizenship &&
      profile.provinceOfOrigin
    );
    
    if (isComplete && !profile.profileCompleted) {
      profile.profileCompleted = true;
      profile.profileCompletedAt = new Date();
    }
  }
  next();
});

// =============================================================================
// Instance Methods
// =============================================================================

userSchema.methods.comparePassword = async function(candidatePassword) {
  return await bcrypt.compare(candidatePassword, this.password);
};

userSchema.methods.getPublicProfile = function() {
  const obj = this.toObject();
  delete obj.password;
  return obj;
};

userSchema.methods.isProfileComplete = function() {
  if (this.role !== UserRole.STUDENT) return true;
  return this.studentProfile?.profileCompleted || false;
};

// Get full name
userSchema.methods.getFullName = function() {
  const profile = this.role === UserRole.STUDENT ? this.studentProfile : this.adminProfile;
  if (!profile) return '';
  
  const parts = [profile.firstName, profile.middleName, profile.lastName, profile.suffix].filter(Boolean);
  return parts.join(' ');
};

// =============================================================================
// Static Methods
// =============================================================================

userSchema.statics.findByStudentNumber = function(studentNumber) {
  return this.findOne({ 'studentProfile.studentNumber': studentNumber });
};

userSchema.statics.findByCollege = function(college) {
  return this.find({ 
    role: UserRole.STUDENT,
    'studentProfile.college': college 
  });
};

userSchema.statics.findByProvince = function(province) {
  return this.find({
    role: UserRole.STUDENT,
    'studentProfile.provinceOfOrigin': province
  });
};

userSchema.statics.findEligibleStudents = function(criteria) {
  const query = { role: UserRole.STUDENT, isActive: true };
  
  if (criteria.maxGWA) {
    query['studentProfile.gwa'] = { $lte: criteria.maxGWA };
  }
  if (criteria.college) {
    query['studentProfile.college'] = criteria.college;
  }
  if (criteria.classification) {
    query['studentProfile.classification'] = { $in: criteria.classification };
  }
  if (criteria.maxIncome) {
    query['studentProfile.annualFamilyIncome'] = { $lte: criteria.maxIncome };
  }
  
  return this.find(query);
};

// =============================================================================
// Export
// =============================================================================

const User = mongoose.model('User', userSchema);

module.exports = {
  User,
  UserRole,
  YearLevel,
  Classification,
  UPLBCollege,
  STBracket,
  AdminAccessLevel,
  Citizenship,
  PhilippineProvinces
};
